#!/usr/bin/env bash
#Write a Bash script that transfers a file from our client to a server:

if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

file_path=$1
ip=$2
username=$3
ssh_path=$4

scpo -o "StrictHostKeyChecking=no" -i "$ssh_path" "$file_path" "$username@$ip:~/"

if [ $? -eq 0 ]
then
	echo "successful"
else
	echo "failed"
fi
