#!/usr/bin/env bash
#update the package list

sudo apt-get update

sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/ethiopro permanent;"

sudo sed -i "s#server_name _;#$string_for_replacement#" /etc/nginx/sites-enabled/default

# Restart Nginx to apply the changes
sudo service nginx restart

