#!/usr/bin/env bash
# Update the package list

sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Create a simple "Hello World!" HTML file
echo "Hello World!" | sudo tee /var/www/html/index.html

# Configure the redirect
string_for_redirect="server_name _;\n\trewrite ^/redirect_me https://github.com/ethiopro permanent;"
sudo sed -i "s#server_name _;#$string_for_redirect#" /etc/nginx/sites-enabled/default

# Create a custom 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
string_for_404="listen 80 default_server;\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}"
sudo sed -i "s#listen 80 default_server;#$string_for_404#" /etc/nginx/sites-enabled/default

# Restart Nginx to apply the changes
sudo service nginx restart
