#!/usr/bin/env bash

# Update the package list
sudo apt-get update

# Install required packages
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.7
sudo apt-get update
sudo apt-get install -y haproxy

# Create or overwrite HAProxy configuration
echo "frontend web-front
        bind *:80
        default_backend web-backend

backend web-backend
        balance roundrobin
        server web1 54.164.28.87 check
        server web2 100.26.164.50 check
" | sudo tee /etc/haproxy/haproxy.cfg

# Start HAProxy service
sudo service haproxy start
