#!/usr/bin/env bash

# Find the PID(s) of the '4-to_infinity_and_beyond' process
self_pid=$$
pids=$(pgrep -f "4-to_infinity_and_beyond" | grep -vw "$self_pid")

if [ -n "$pids" ]; then
  kill $pids
else
  echo "No running 4-to_infinity_and_beyond process found."
fi
