#!/usr/bin/env bash
# Check if /etc/passwd exists
if [ ! -f "/etc/passwd" ]; then
  echo "Error: /etc/passwd file not found."
  exit 1
fi

# Read and display the content of /etc/passwd using while loop and IFS
while IFS=":" read -r username _ uid gid _ home shell; do
  echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode x, more info about the user here: $uid INFO"
done < "/etc/passwd"
