#!/usr/bin/env bash
# A Bash script that gives you information about the school file.

school="school"  # Replace "school" with the actual filename you want to check

if [[ -e "$school" ]]; then
    echo "school file exists"
    if [[ -s "$school" ]]; then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi

    if [[ -f "$school" ]]; then
        echo "school is a regular file"
    else
        # Do nothing if the file is not a regular file
        :
    fi
else
    echo "school file does not exist"
fi
