#!/usr/bin/env bash
# Check if running in Docker
if [ -f "/.dockerenv" ]; then
    echo "Running in Docker environment"
else
    echo "Not running in Docker environment"
    exit 1
fi

# Update /etc/hosts to change localhost IP
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts > /dev/null

# Update /etc/hosts to change facebook.com IP
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null

echo "Configuration completed"
