#!/usr/bin/env bash
# Your machine has an SSH configuration file for the local SSH client

Host *
	PasswordAuthentication no
	IdentityFile ~/.ssh/school
	SendEnv LANG LC_*
	HashKnownHosts yes
	GSSAPIAuthentication yes
	GSSAPIDelegateCredentials no
